- module: system
  metricsets:
    - core
    - cpu
    - load
    - diskio
    - filesystem
    - fsstat
    - memory
    - network
    - process
    - socket
  enabled: true
  period: 10s
  processes: ['.*']
  cpu_ticks: true
  process.cgroups.enabled: true
  process.include_top_n:
    enabled: true
    by_cpu: 20
    by_memory: 20
